version: '3'
services:
  chess:
    build: .
    container_name: chess
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
    links:
      - mongo
    depends_on: 
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=docker_chess
    command: sh -c "/wait && node server/build/index.js" 
  mongo:
    hostname: mongo
    image: mongo
    container_name: mongo_chess
    ports: 
      - "29017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
