version: '3'
services: 
  chess:
    build: .
    container_name: chess
    ports:
      - "3000:3000"
    restart: always
    env_file: .env
    environment:
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - app-network
    depends_on: 
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    command: sh -c "/wait && node server/build/index.js"
  mongo:
    image: mongo
    container_name: $MONGO_HOST
    ports: 
      - "$MONGO_PORT:27017"
    env_file: .env
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
