version: '3'
services: 
  chess:
    build: .
    container_name: chess
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    environment:
      WAIT_HOSTS: mongo:27017
    networks:
      - app-network
    depends_on: 
      - mongo
  mongo:
    image: mongo
    container_name: $MONGO_HOST
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
